version: '2'

services:
    ynfinite-client:
        build:
            context: ../../
            dockerfile: development/docker/Dockerfile-apache
        ports:
            - 80:80
        volumes:
            - ${APP_PATH}:/var/www
        networks:
            - ynfinite
        links:
            - db
        depends_on:
            - db

    db:
        image: mysql/mysql-server:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'myDb'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'test'
            MYSQL_ROOT_PASSWORD: 'test'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        networks:
            - ynfinite

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        depends_on:
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'test'
            MYSQL_ROOT_PASSWORD: 'test'
            PMA_HOST: 'db'
            PMA_PORT: 3306
        networks:
            - ynfinite

networks:
    ynfinite:
        external:
            name: ${COMPOSE_PROJECT_NAME}_ynfinite
