FROM php:8.1-apache

RUN a2enmod rewrite expires

RUN apt-get update && apt-get install -y \
    zip \
    zlib1g \
    zlib1g-dev \
    libicu-dev \
    g++ \
    unzip \
    curl \
    git \
    build-essential \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*

RUN pecl install apcu

RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install gettext

RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN docker-php-ext-enable intl

RUN docker-php-ext-enable apcu



RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf

RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

ADD development/docker/localhost /etc/apache2/sites-available/000-default.conf
ADD composer.json /var/www/composer.json

WORKDIR /var/www

RUN composer install

EXPOSE 80



